### ISSUE TITLE
Typo in shortcut.BACKSLASH

### ISSUE THREAD

**Issue by p9-metis** [cubait/cuba-translation-it#2]
Hi Paolo,
I think there's a small typo in your translation files (modules/gui/src/com/haulmont/cuba/gui/messages_it.properties and modules/web/src/com/haulmont/cuba/gui/messages_it.properties)

the row:

`shortcut.BACKSLASH = \`

should be:

`shortcut.BACKSLASH = \\`

**Comment by pfurini** [comment]
Fixed by #3
